package io.hatis.db

class DbUtilsException(cause: Throwable): RuntimeException(cause)